from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Tuple


@dataclass(frozen=True)
class SourceContract:
    source_path: str
    owner_flow: str
    phase1_requirement: str
    required_columns: Tuple[str, ...]
    fallback_rules: Tuple[str, ...]
    must_not_duplicate: Tuple[str, ...]


_SOURCE_CONTRACTS: Dict[str, SourceContract] = {
    "supplier_discovery_handoff": SourceContract(
        source_path="out/systems/F/inbox/supplier_discovery_handoff.csv",
        owner_flow="supplier_discovery",
        phase1_requirement="mandatory",
        required_columns=(
            "discovery_candidate_id",
            "discovery_run_id",
            "asin",
            "barcode",
            "brand",
            "chosen_supplier_id",
            "chosen_supplier_name",
            "price_list_status",
            "price_list_artifact_path",
            "handoff_ready_flag",
            "last_reviewed_utc",
        ),
        fallback_rules=(
            "No safe fallback exists for feeder intake when supplier handoff is missing or contract-invalid.",
            "Rows that fail contract checks must stay in holds with explicit reason codes.",
        ),
        must_not_duplicate=(
            "supplier_discovery_handoff_contract_truth",
            "supplier_price_list_path_truth",
        ),
    ),
    "supplier_price_list_universal_live": SourceContract(
        source_path="out/systems/F/inbox/supplier_price_list_universal_live.csv",
        owner_flow="F_supplier_converter",
        phase1_requirement="mandatory",
        required_columns=(
            "supplier_id",
            "supplier_name",
            "supplier_sku",
            "supplier_title",
            "barcode",
            "unit_cost",
            "currency",
            "vat_rate",
            "source_url",
            "source_file_path",
            "source_seen_at_utc",
            "row_hash",
            "is_valid_source_row",
            "normalized_utc",
        ),
        fallback_rules=(
            "No safe fallback exists for shared pass logic when universal supplier input is missing or contract-invalid.",
            "Rows that fail shared pass logic must remain explicit in holds with reason codes.",
        ),
        must_not_duplicate=(
            "supplier_universal_contract_truth",
            "shared_pass_logic_decision_truth",
        ),
    ),
    "feeder_shared_pass_logic_live": SourceContract(
        source_path="out/systems/F/live/feeder_shared_pass_logic_live.csv",
        owner_flow="F_shared_pass_logic",
        phase1_requirement="mandatory",
        required_columns=(
            "feeder_candidate_id",
            "supplier_id",
            "supplier_name",
            "supplier_sku",
            "supplier_title",
            "barcode",
            "unit_cost",
            "currency",
            "vat_rate",
            "pass_logic_status",
            "pass_logic_reason_codes",
            "legacy_status_code",
            "ready_for_amazon_checks_flag",
            "manual_review_flag",
            "hold_flag",
            "pass_logic_utc",
            "source_row_hash",
            "source_file_path",
            "source_seen_at_utc",
        ),
        fallback_rules=(
            "No safe fallback exists for recommendation and approval queue build when shared pass logic input is missing or contract-invalid.",
            "Rows that fail recommendation checks must stay explicit in queue or decision lineage with reason codes.",
        ),
        must_not_duplicate=(
            "shared_pass_logic_contract_truth",
            "approval_queue_decision_truth",
        ),
    ),
    "feeder_approval_queue_live": SourceContract(
        source_path="out/systems/F/live/feeder_approval_queue_live.csv",
        owner_flow="F_approval_queue",
        phase1_requirement="mandatory",
        required_columns=(
            "queue_utc",
            "candidate_id",
            "feeder_candidate_id",
            "supplier_id",
            "supplier_name",
            "supplier_sku",
            "supplier_title",
            "recommendation_status",
            "recommended_test_qty",
            "queue_status",
            "decision_status",
            "approval_required_flag",
            "owner",
            "snooze_until_utc",
            "source_row_hash",
            "source_file_path",
            "source_seen_at_utc",
        ),
        fallback_rules=(
            "No safe fallback exists for PO handoff when feeder approval queue input is missing or contract-invalid.",
            "Non-ready rows must remain explicit in PO handoff holds with reason codes.",
        ),
        must_not_duplicate=(
            "approval_queue_contract_truth",
            "po_handoff_routing_truth",
        ),
    ),
    "feeder_approval_decisions_log": SourceContract(
        source_path="out/systems/F/history/feeder_approval_decisions_log.csv",
        owner_flow="F_approval_queue",
        phase1_requirement="mandatory",
        required_columns=(
            "decision_utc",
            "event_id",
            "candidate_id",
            "feeder_candidate_id",
            "decision_action",
            "final_decision_status",
            "decision_source",
            "recommendation_status",
            "recommended_test_qty",
            "actor",
            "decision_note",
            "source_row_hash",
            "source_file_path",
            "source_seen_at_utc",
        ),
        fallback_rules=(
            "No safe fallback exists for approved-only PO handoff when decision lineage is missing or contract-invalid.",
            "Rows without valid approval lineage must remain explicit in PO handoff holds with reason codes.",
        ),
        must_not_duplicate=(
            "approval_decision_lineage_truth",
            "po_handoff_approval_truth",
        ),
    ),
    "feeder_candidate_recommendations_live": SourceContract(
        source_path="out/systems/F/live/feeder_candidate_recommendations_live.csv",
        owner_flow="F_approval_queue",
        phase1_requirement="mandatory",
        required_columns=(
            "candidate_id",
            "feeder_candidate_id",
            "supplier_id",
            "supplier_name",
            "supplier_sku",
            "supplier_title",
            "barcode",
            "unit_cost",
            "currency",
            "vat_rate",
            "viability_status",
            "viability_reason_codes",
            "estimated_demand",
            "estimated_roi_pct",
            "estimated_margin_gbp",
            "recommended_test_qty",
            "recommendation_status",
            "recommendation_reason_codes",
            "approval_required_flag",
            "decision_status",
            "recommendation_utc",
            "source_row_hash",
            "source_file_path",
            "source_seen_at_utc",
        ),
        fallback_rules=(
            "No safe fallback exists for local sheet-style review build when recommendations input is missing or contract-invalid.",
            "Rows without recommendation context must remain explicit in review outputs with reason codes.",
        ),
        must_not_duplicate=(
            "recommendation_contract_truth",
            "legacy_sheet_review_truth",
        ),
    ),
    "feeder_legacy_chart_daily_raw_live": SourceContract(
        source_path="out/systems/F/live/feeder_legacy_chart_daily_raw_live.csv",
        owner_flow="F_legacy_scrape",
        phase1_requirement="mandatory",
        required_columns=(
            "observed_utc",
            "asin",
            "day",
            "amazon_price_raw",
            "fba_price_raw",
            "fbm_price_raw",
            "buy_box_price_raw",
            "bsr_raw",
            "price_chosen_processed",
            "phase_processed",
        ),
        fallback_rules=(
            "No safe fallback exists for backtest input build when legacy chart history is missing.",
            "Backtest input build should fail fast when core chart history columns are missing.",
        ),
        must_not_duplicate=(
            "legacy_chart_backtest_truth",
            "asin_day_market_history_truth",
        ),
    ),
    "feeder_legacy_scrape_evidence_live": SourceContract(
        source_path="out/systems/F/live/feeder_legacy_scrape_evidence_live.csv",
        owner_flow="F_legacy_scrape",
        phase1_requirement="optional",
        required_columns=(
            "observed_utc",
            "asin",
            "supplier_id",
            "supplier_name",
            "supplier_sku",
            "break_even",
            "monthly_sold",
            "bbp_monthly_units_chosen",
        ),
        fallback_rules=(
            "If legacy scrape evidence is missing, fallback mapping should continue with no_product_db_match.",
            "Do not synthesize legacy supplier identity when no evidence row exists.",
        ),
        must_not_duplicate=(
            "legacy_scrape_identity_truth",
            "legacy_backtest_evidence_projection_truth",
        ),
    ),
    "feeder_legacy_first_checks_live": SourceContract(
        source_path="out/systems/F/live/feeder_legacy_first_checks_live.csv",
        owner_flow="F_legacy_scrape",
        phase1_requirement="optional",
        required_columns=(
            "asin",
            "supplier",
            "supplier_sku",
            "cost",
            "break_even",
        ),
        fallback_rules=(
            "If legacy first-check costs are missing, keep fallback rows with manual review for missing supplier cost.",
            "Do not infer supplier cost from market price when first-check cost is unavailable.",
        ),
        must_not_duplicate=(
            "legacy_first_check_cost_truth",
            "legacy_cost_projection_truth",
        ),
    ),
    "f_screening_row_state_live": SourceContract(
        source_path="out/systems/F/live/f_screening_row_state_live.csv",
        owner_flow="F_legacy_scrape",
        phase1_requirement="optional",
        required_columns=(
            "observed_utc",
            "supplier_id",
            "supplier_name",
            "supplier_sku",
            "candidate_id",
            "row_status",
            "last_stage",
            "fail_code",
            "attempt_count",
            "timeout_until_utc",
            "mode",
            "updated_at_utc",
        ),
        fallback_rules=(
            "If canonical screening state is missing, fallback readers may continue from legacy first-check/scrape outputs.",
            "Do not synthesize timeout state when canonical row state is unavailable.",
        ),
        must_not_duplicate=(
            "f061_screening_row_truth",
            "derived_screening_projection_truth",
        ),
    ),
    "product_db_preview": SourceContract(
        source_path="out/product_db_preview.csv",
        owner_flow="A/B integration snapshot",
        phase1_requirement="optional",
        required_columns=(
            "seller_sku",
            "asin",
            "supplier_code",
            "supplier_name",
            "supplier_catalog_price",
            "last_purchase_price",
            "sale_status",
        ),
        fallback_rules=(
            "If product_db_preview is missing, input rows should continue with mapping_status=no_product_db_match.",
            "No synthetic SKU identity should be created when product identity source is missing.",
        ),
        must_not_duplicate=(
            "product_identity_truth",
            "supplier_identity_projection_truth",
        ),
    ),
    "sku_sales_velocity": SourceContract(
        source_path="out/sku_sales_velocity.csv",
        owner_flow="E",
        phase1_requirement="optional",
        required_columns=(
            "sku",
            "window_days",
            "units_sold",
            "velocity_units_per_day",
        ),
        fallback_rules=(
            "If sales velocity is missing, keep rows with reduced confidence and manual review flags.",
            "Do not infer demand precision when no SKU-level velocity row exists.",
        ),
        must_not_duplicate=(
            "e_velocity_truth",
            "listing_velocity_projection_truth",
        ),
    ),
    "sku_performance_summary": SourceContract(
        source_path="out/sku_performance_summary.csv",
        owner_flow="E",
        phase1_requirement="optional",
        required_columns=(
            "sku",
            "expected_refund_cost_per_unit_gbp",
            "break_even_price_gbp",
        ),
        fallback_rules=(
            "If performance summary is missing, keep rows with reduced confidence and leave economics fields blank.",
            "Do not block backtest input rows solely due to missing economics context file.",
        ),
        must_not_duplicate=(
            "e_economics_truth",
            "break_even_projection_truth",
        ),
    ),
    "listing_offer_snapshot_latest": SourceContract(
        source_path="out/listing_offer_snapshot_latest.csv",
        owner_flow="H",
        phase1_requirement="optional",
        required_columns=(
            "timestamp_utc",
            "asof_date",
            "sku",
            "asin",
            "our_price",
            "buy_box_price",
            "buy_box_present_flag",
            "lowest_fba_price",
        ),
        fallback_rules=(
            "If listing offer snapshot is missing, continue backtest input build without optional live market context.",
            "Historical replay inputs must not be replaced by missing current offer context.",
        ),
        must_not_duplicate=(
            "h_offer_snapshot_truth",
            "current_market_context_support_truth",
        ),
    ),
    "feeder_backtest_policy_live": SourceContract(
        source_path="out/systems/F/live/feeder_backtest_policy_live.csv",
        owner_flow="F_backtest_policy",
        phase1_requirement="mandatory",
        required_columns=(
            "observed_utc",
            "policy_id",
            "policy_version",
            "policy_status",
            "minimum_expected_profit_gbp",
            "entry_target_roi_pct",
            "working_floor_roi_pct",
            "exit_floor_roi_pct",
            "emergency_floor_roi_pct",
            "recency_weight_30d",
            "recency_weight_90d",
            "recency_weight_180d",
            "recency_weight_365d",
            "ceiling_warn_ratio_30d",
            "ceiling_red_ratio_30d",
            "ceiling_extreme_ratio_30d",
            "shock_trigger_pct_1d",
            "shared_sales_default_pct",
        ),
        fallback_rules=(
            "No safe fallback exists for replay when active backtest policy is missing.",
            "Replay must fail fast when policy contract columns are missing.",
        ),
        must_not_duplicate=(
            "backtest_policy_profile_truth",
            "policy_control_surface_truth",
        ),
    ),
    "feeder_backtest_input_view_live": SourceContract(
        source_path="out/systems/F/live/feeder_backtest_input_view_live.csv",
        owner_flow="F_backtest_input",
        phase1_requirement="mandatory",
        required_columns=(
            "observed_utc",
            "policy_id",
            "seller_sku",
            "asin",
            "mapping_status",
            "input_status",
            "input_reason_codes",
            "history_days",
            "paired_buy_box_bsr_days",
            "buy_box_coverage_share",
            "demand_basis_source",
            "demand_basis_units_monthly",
            "demand_basis_month_label",
            "bbp_sales_last_completed_month_label",
            "bbp_sales_last_completed_month_units",
            "bbp_sales_current_month_label",
            "bbp_sales_current_month_units",
            "bbp_sales_future_month_count_ignored",
            "bbp_sales_replay_demand_basis_source",
            "bbp_sales_replay_demand_basis_label",
            "bbp_sales_replay_demand_basis_units",
            "base_velocity_30d_units_per_day",
            "current_supplier_buy_cost_gbp",
            "break_even_price_gbp",
            "market_price_gbp",
            "seasonality_state",
            "seasonality_reason_codes",
            "stability_state",
            "stability_reason_codes",
            "recent_vs_baseline_state",
            "recent_vs_baseline_reason_codes",
            "completed_months_count",
            "history_maturity_state",
            "history_confidence",
            "price_qualified_units_monthly",
            "price_qualified_profit_monthly_gbp",
            "price_qualification_reason_codes",
            "qualification_market_gate_state",
            "qualification_market_gate_factor",
            "qualification_amazon_pressure_factor",
            "qualification_buy_box_coverage_factor",
            "qualification_maturity_factor",
            "qualification_final_factor",
            "qualification_zero_or_block_reason",
            "manual_review_flag",
        ),
        fallback_rules=(
            "No safe fallback exists for replay when prepared input view is missing.",
            "Replay should only run on rows with input_status=ready and valid contract fields.",
        ),
        must_not_duplicate=(
            "backtest_input_row_truth",
            "sku_asin_policy_replay_input_truth",
        ),
    ),
    "feeder_backtest_replay_daily_live": SourceContract(
        source_path="out/systems/F/live/feeder_backtest_replay_daily_live.csv",
        owner_flow="F_backtest_replay",
        phase1_requirement="mandatory",
        required_columns=(
            "observed_utc",
            "policy_id",
            "seller_sku",
            "asin",
            "day",
            "replay_status",
            "competition_scenario",
            "replay_mode",
            "price_zone",
            "sales_share_pct",
            "estimated_units_ours",
            "estimated_profit_gbp",
            "failure_event_flag",
            "demand_basis_source",
            "demand_basis_units_monthly",
            "seasonality_state",
            "seasonality_reason_codes",
            "stability_state",
            "stability_reason_codes",
            "recent_vs_baseline_state",
            "recent_vs_baseline_reason_codes",
            "completed_months_count",
            "history_maturity_state",
            "raw_demand_units_monthly",
            "price_qualified_units_monthly",
            "price_qualified_profit_monthly_gbp",
            "price_qualification_reason_codes",
            "qualification_market_gate_state",
            "qualification_market_gate_factor",
            "qualification_amazon_pressure_factor",
            "qualification_buy_box_coverage_factor",
            "qualification_maturity_factor",
            "qualification_final_factor",
            "qualification_zero_or_block_reason",
            "qualification_value_source",
        ),
        fallback_rules=(
            "No safe fallback exists for summary build when replay daily output is missing.",
            "Summary must fail fast when replay grain contract is missing.",
        ),
        must_not_duplicate=(
            "backtest_daily_replay_truth",
            "sku_asin_day_replay_outcome_truth",
        ),
    ),
}


def get_f_source_contracts() -> Dict[str, SourceContract]:
    return dict(_SOURCE_CONTRACTS)


def get_source_contract(name: str) -> SourceContract:
    if name not in _SOURCE_CONTRACTS:
        available = ",".join(sorted(_SOURCE_CONTRACTS.keys()))
        raise ValueError(f"unknown F source contract '{name}', expected one of: {available}")
    return _SOURCE_CONTRACTS[name]
