:: Operational entrypoint - do not bypass; use for all runs.
@echo off
setlocal
set "PY=C:\Users\Luke\AppData\Local\Programs\Python\Python312\python.exe"
if not exist "%PY%" set "PY=python"
set "ROOT=%~dp0"
set "PYTHONPATH=%ROOT%;%ROOT%scripts;%PYTHONPATH%"
if not defined SELLERONE_STORAGE_MODE set "SELLERONE_STORAGE_MODE=sql_primary_csv_export"
if not defined SELLERONE_SQLITE_PATH set "SELLERONE_SQLITE_PATH=out/sql/sellerone_dev.sqlite3"
set "A_LIVE=%ROOT%out\systems\A\live"
set "B_LIVE=%ROOT%out\systems\B\live"
set "INVENTORY_USE_API_OWNER=1"
if not exist "%A_LIVE%" mkdir "%A_LIVE%"
if not exist "%B_LIVE%" mkdir "%B_LIVE%"
set "RUN_LOCK_PATH=%A_LIVE%\run_cycle.lock"
set "B_CYCLE_LOCK_PATH=%B_LIVE%\B_cycle.lock"
if not defined A_SKIP_LEGACY_SHEET_OUTPUT_STEPS set "A_SKIP_LEGACY_SHEET_OUTPUT_STEPS=1"
if not defined A_ENABLE_STOCK_RECEIPTS_SHEET set "A_ENABLE_STOCK_RECEIPTS_SHEET=0"
if not defined A_MAINT_POLL_S set "A_MAINT_POLL_S=5"
if not defined A_MAINT_WAIT_READY_MAX_S set "A_MAINT_WAIT_READY_MAX_S=300"
if not defined A_MAINT_WAIT_LOG_EVERY_S set "A_MAINT_WAIT_LOG_EVERY_S=10"
if not defined A_MAINT_B_NOT_RUNNING_STABLE_S set "A_MAINT_B_NOT_RUNNING_STABLE_S=30"
if not defined A_ENSURE_B_AFTER_A set "A_ENSURE_B_AFTER_A=0"
if not defined A_B_RECOVERY_WAIT_S set "A_B_RECOVERY_WAIT_S=60"
if not defined A_B_RECOVERY_POLL_S set "A_B_RECOVERY_POLL_S=5"
if not defined A_B_RECOVERY_USE_SCHEDULER set "A_B_RECOVERY_USE_SCHEDULER=1"
if not defined A_B_SCHEDULER_TASK_NAME set "A_B_SCHEDULER_TASK_NAME=AMZ Orders"
"%PY%" "%ROOT%scripts\cycles\run_A_all.py"
endlocal
