from __future__ import annotations

import csv
import json
import os
import re
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .paths import get_manager_paths


CONTROL_STATE_REL_PATH = Path("sellerone_manager") / "CONTROL" / "CURRENT_STATE.md"

ACTIVE_STATUSES = {"approved", "in_progress", "fixed_needs_retest", "retest_failed", "reopened"}
BLOCKED_STATUSES = {"blocked_needs_luke"}
TERMINAL_STATUSES = {"proved", "parked"}
STATUS_LABELS = {
    "approved": "approved",
    "in_progress": "in progress",
    "fixed_needs_retest": "waiting proof",
    "retest_failed": "proof failed",
    "reopened": "reopened",
    "blocked_needs_luke": "Luke-blocked",
    "parked": "parked",
    "proved": "proved",
}
PROTECTED_BOUNDARIES = [
    "no worker cycle starts or restarts",
    "no price changes",
    "no queue edits",
    "no Google Sheets writes",
    "no Product DB or local DB alignment",
    "no output deletion",
    "no purchase, receiving, or send-to-Amazon actions",
    "no Amazon security bypass",
    "no automation restarts",
]


@dataclass(frozen=True)
class CurrentStateMarkdownResult:
    path: Path
    markdown: str
    generated_utc: str
    recommended_next_task: str
    active_automation_count: int
    active_work_count: int
    blocked_work_count: int


def utc_now_text() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def build_current_state_markdown(
    *,
    root: Path | str | None = None,
    generated_utc: str | None = None,
    automation_root: Path | str | None = None,
) -> CurrentStateMarkdownResult:
    paths = get_manager_paths(root)
    generated = generated_utc or utc_now_text()
    control_dir = paths.root / "sellerone_manager" / "CONTROL"
    state_path = paths.root / CONTROL_STATE_REL_PATH

    packet_rows = _read_csv_rows(paths.output_dir / "approved_task_packets.csv")
    mot_summary = _read_mot_summary(paths.output_dir / "mot")
    automation_summary = _read_automation_summary(automation_root, control_dir=control_dir)
    adr_summary = _read_architecture_decisions(control_dir / "ARCHITECTURE_DECISIONS.md")

    status_counts = Counter(row.get("status", "").strip() or "missing" for row in packet_rows)
    active_work = [
        row
        for row in packet_rows
        if row.get("status") in ACTIVE_STATUSES and _text(row.get("luke_action_required")) != "1"
    ]
    blocked_work = [
        row
        for row in packet_rows
        if row.get("status") in BLOCKED_STATUSES or _text(row.get("luke_action_required")) == "1"
    ]
    active_work = sorted(active_work, key=_work_sort_key)
    blocked_work = sorted(blocked_work, key=_work_sort_key)

    archive_path = paths.root / "sellerone_manager" / "tasks" / "archive"
    recommended_next = _recommended_next_task(
        control_dir=control_dir,
        unapproved_active_automation_count=automation_summary["unapproved_active_count"],
    )
    phase_detail = _phase_detail(control_dir)

    plain_status = _plain_status(
        mot_summary=mot_summary,
        active_automation_count=automation_summary["active_count"],
        approved_active_automation_count=automation_summary["approved_active_count"],
        unapproved_active_automation_count=automation_summary["unapproved_active_count"],
        active_work_count=len(active_work),
        blocked_work_count=len(blocked_work),
        recommended_next=recommended_next,
    )

    lines = [
        "# SellerOne Current State",
        "",
        f"Generated UTC: {generated}",
        "Generated by: `sellerone_manager.current_state_markdown`",
        "",
        "## Plain-English Status",
        "",
        plain_status,
        "",
        "## Current Phase",
        "",
        "- Phase: `SellerOne 2.1 - Control Desk Stabilisation`",
        f"- Detail: {phase_detail}",
        "- Operating shape: Luke talks to Rep; Operations reports feed Rep; queue owns work; Builders and Reviewers work tickets.",
        "",
        "## Queue Summary",
        "",
        "- Canonical queue: approved task packet system",
        "- Queue source: `sellerone_manager/tasks/` plus generated packet index",
        f"- Packet index rows: {len(packet_rows)}",
        f"- Approved: {status_counts.get('approved', 0)}",
        f"- In progress: {status_counts.get('in_progress', 0)}",
        f"- Waiting proof: {status_counts.get('fixed_needs_retest', 0)}",
        f"- Proof failed: {status_counts.get('retest_failed', 0)}",
        f"- Reopened: {status_counts.get('reopened', 0)}",
        f"- Luke-blocked: {status_counts.get('blocked_needs_luke', 0)}",
        f"- Parked: {status_counts.get('parked', 0)}",
        f"- Proved: {status_counts.get('proved', 0)}",
        f"- Archive folder: {'present' if archive_path.exists() else 'missing'}",
        "",
        "## Health Summary",
        "",
        f"- Latest MOT observed UTC: {mot_summary['observed_utc']}",
        f"- MOT status: `{mot_summary['status']}`",
        f"- Fails: {mot_summary['fail_count']}",
        f"- Warnings: {mot_summary['warn_count']}",
        f"- Decisions: {mot_summary['decision_count']}",
        f"- Not checked: {mot_summary['not_checked_count']}",
        "",
    ]
    lines.extend(_format_problem_rows("Top Failed Checks", mot_summary["fail_rows"]))
    lines.extend(_format_problem_rows("Top Decision Checks", mot_summary["decision_rows"]))
    lines.extend(
        [
            "## Active Work",
            "",
        ]
    )
    lines.extend(_format_work_rows(active_work, empty_message="No active Builder work is currently ready in the packet index."))
    lines.extend(
        [
            "",
            "## Blocked Work",
            "",
        ]
    )
    lines.extend(_format_work_rows(blocked_work, empty_message="No Luke-blocked packets are currently visible in the packet index."))
    lines.extend(
        [
            "",
            "## Operations State",
            "",
            f"- Codex automations found: {automation_summary['total_count']}",
            f"- Active automations: {automation_summary['active_count']}",
            f"- Approved active pilot automations: {automation_summary['approved_active_count']}",
            f"- Unapproved active automations: {automation_summary['unapproved_active_count']}",
            f"- Paused automations: {automation_summary['paused_count']}",
            f"- Architecture decisions recorded: {adr_summary['count']}",
        ]
    )
    if adr_summary["latest"]:
        lines.append(f"- Latest architecture decision: {adr_summary['latest']}")
    if automation_summary["approved_active_names"]:
        lines.extend(["", "Approved active pilot automations:"])
        for name in automation_summary["approved_active_names"][:5]:
            lines.append(f"- {name}")
    if automation_summary["unapproved_active_names"]:
        lines.extend(["", "Active automations needing review:"])
        for name in automation_summary["unapproved_active_names"][:5]:
            lines.append(f"- {name}")
    lines.extend(
        [
            "",
            "## Recommended Next Task",
            "",
            f"- `{recommended_next}`",
            f"- Reason: {_recommended_reason(recommended_next)}",
            "",
            "## Protected Boundaries",
            "",
        ]
    )
    for boundary in PROTECTED_BOUNDARIES:
        lines.append(f"- {boundary}")
    lines.extend(
        [
            "",
            "## Evidence Inputs",
            "",
            "- MOT evidence: `out/systems/M/mot/`",
            "- Packet index: `out/systems/M/approved_task_packets.csv`",
            "- Blocked packet evidence: packet status and `sellerone_manager/tasks/blocked/`",
            "- Automation state: Codex app automation definitions",
            "- Architecture decisions: `sellerone_manager/CONTROL/ARCHITECTURE_DECISIONS.md`",
            "",
            "## State Rule",
            "",
            "`CURRENT_STATE.md` is the human-readable state anchor. `current_state.json` is machine support only and must not outrank newer MOT or packet evidence.",
        ]
    )

    markdown = "\n".join(lines).rstrip() + "\n"
    return CurrentStateMarkdownResult(
        path=state_path,
        markdown=markdown,
        generated_utc=generated,
        recommended_next_task=recommended_next,
        active_automation_count=automation_summary["active_count"],
        active_work_count=len(active_work),
        blocked_work_count=len(blocked_work),
    )


def write_current_state_markdown(
    *,
    root: Path | str | None = None,
    generated_utc: str | None = None,
    automation_root: Path | str | None = None,
) -> CurrentStateMarkdownResult:
    result = build_current_state_markdown(root=root, generated_utc=generated_utc, automation_root=automation_root)
    result.path.parent.mkdir(parents=True, exist_ok=True)
    result.path.write_text(result.markdown, encoding="utf-8")
    return result


def format_current_state_markdown_status(result: CurrentStateMarkdownResult) -> str:
    return "\n".join(
        [
            "status=written",
            f"path={result.path}",
            f"generated_utc={result.generated_utc}",
            f"recommended_next_task={result.recommended_next_task}",
            f"active_automations={result.active_automation_count}",
            f"active_work={result.active_work_count}",
            f"blocked_work={result.blocked_work_count}",
        ]
    )


def _read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        return [{key: value or "" for key, value in row.items()} for row in reader]


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return payload if isinstance(payload, dict) else {}


def _read_mot_summary(mot_dir: Path) -> dict[str, Any]:
    json_payload = _read_json(mot_dir / "mot_latest.json")
    if json_payload:
        rows = json_payload.get("rows") if isinstance(json_payload.get("rows"), list) else []
        fail_rows = [row for row in rows if isinstance(row, dict) and row.get("status") == "fail"]
        decision_rows = [
            row
            for row in rows
            if isinstance(row, dict) and (row.get("status") == "decision_needed" or row.get("luke_action_required") == "1")
        ]
        return {
            "observed_utc": _text(json_payload.get("observed_utc")) or "unknown",
            "status": _text(json_payload.get("status")) or "unknown",
            "fail_count": _int_text(json_payload.get("fail_count")),
            "warn_count": _int_text(json_payload.get("warn_count")),
            "decision_count": _int_text(json_payload.get("decision_count")),
            "not_checked_count": _int_text(json_payload.get("not_checked_count")),
            "fail_rows": fail_rows[:5],
            "decision_rows": decision_rows[:5],
        }

    rows = _read_csv_rows(mot_dir / "mot_latest.csv")
    counts = Counter(row.get("status", "missing") for row in rows)
    fail_rows = [row for row in rows if row.get("status") == "fail"]
    decision_rows = [
        row for row in rows if row.get("status") == "decision_needed" or row.get("luke_action_required") == "1"
    ]
    return {
        "observed_utc": _latest_observed(rows) or "missing",
        "status": _status_from_counts(counts),
        "fail_count": str(counts.get("fail", 0)),
        "warn_count": str(counts.get("warn", 0)),
        "decision_count": str(counts.get("decision_needed", 0) + len([row for row in rows if row.get("luke_action_required") == "1"])),
        "not_checked_count": str(counts.get("not_checked", 0)),
        "fail_rows": fail_rows[:5],
        "decision_rows": decision_rows[:5],
    }


def _read_automation_summary(automation_root: Path | str | None, *, control_dir: Path) -> dict[str, Any]:
    root = _resolve_automation_root(automation_root)
    rows: list[dict[str, str]] = []
    if root and root.exists():
        for path in sorted(root.rglob("automation.toml")):
            text = path.read_text(encoding="utf-8", errors="ignore")
            rows.append(
                {
                    "id": _toml_field(text, "id") or path.parent.name,
                    "name": _toml_field(text, "name") or path.parent.name,
                    "status": _toml_field(text, "status") or "unknown",
                }
            )
    counts = Counter(row["status"] for row in rows)
    active_rows = [row for row in rows if row["status"] == "ACTIVE"]
    rep_briefing_activation_exists = (control_dir / "SO21_REP_BRIEFING_ACTIVATION.md").exists()
    cleanup_monitor_review_exists = (control_dir / "SO21_AUTOMATION_REVIEW.md").exists()
    approved_active_rows = [
        row
        for row in active_rows
        if _is_approved_active_pilot(
            row,
            rep_briefing_activation_exists=rep_briefing_activation_exists,
            cleanup_monitor_review_exists=cleanup_monitor_review_exists,
        )
    ]
    unapproved_active_rows = [
        row
        for row in active_rows
        if not _is_approved_active_pilot(
            row,
            rep_briefing_activation_exists=rep_briefing_activation_exists,
            cleanup_monitor_review_exists=cleanup_monitor_review_exists,
        )
    ]
    return {
        "total_count": len(rows),
        "active_count": counts.get("ACTIVE", 0),
        "approved_active_count": len(approved_active_rows),
        "unapproved_active_count": len(unapproved_active_rows),
        "paused_count": counts.get("PAUSED", 0),
        "approved_active_names": [row["name"] for row in approved_active_rows],
        "unapproved_active_names": [row["name"] for row in unapproved_active_rows],
    }


def _is_approved_active_pilot(
    row: dict[str, str],
    *,
    rep_briefing_activation_exists: bool,
    cleanup_monitor_review_exists: bool,
) -> bool:
    value = f"{row.get('id', '')} {row.get('name', '')}".lower()
    if "so21-rep-briefing" in value:
        return rep_briefing_activation_exists
    if "so21-cleanup-operations-monitor" in value or "so21 cleanup operations monitor" in value:
        return cleanup_monitor_review_exists
    return False


def _resolve_automation_root(automation_root: Path | str | None) -> Path | None:
    if automation_root is not None:
        return Path(automation_root)
    codex_home = os.environ.get("CODEX_HOME")
    if codex_home:
        return Path(codex_home) / "automations"
    user_profile = os.environ.get("USERPROFILE")
    if user_profile:
        return Path(user_profile) / ".codex" / "automations"
    return None


def _read_architecture_decisions(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"count": 0, "latest": ""}
    titles = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        if line.startswith("## ADR-"):
            titles.append(line.removeprefix("## ").strip())
    return {"count": len(titles), "latest": titles[-1] if titles else ""}


def _recommended_next_task(*, control_dir: Path, unapproved_active_automation_count: int) -> str:
    if not (control_dir / "QUEUE_CONTRACT.md").exists():
        return "SO21-QUEUE-CONTRACT"
    if unapproved_active_automation_count:
        return "SO21-AUTOMATION-REVIEW"
    if not (control_dir / "STORAGE_POLICY.md").exists():
        return "SO21-CUSTODIAN-POLICY"
    if not (control_dir / "CURRENT_TICKETS.md").exists() or not (control_dir / "BACKLOG.md").exists():
        return "SO21-CURRENT-TICKETS-AND-BACKLOG"
    if not (control_dir / "INSTRUCTION_CLEANUP_PLAN.md").exists():
        return "SO21-INSTRUCTION-CLEANUP"
    if not (control_dir / "AI_USAGE.csv").exists():
        return "SO21-AI-USAGE-REPORT"
    if _coding_plan_archive_needed(control_dir):
        return "SO21-CODING-PLAN-ARCHIVE"
    if _prompt_folder_archive_needed(control_dir):
        return "SO21-PROMPT-FOLDER-ARCHIVE"
    if _role_file_trim_needed(control_dir):
        return "SO21-ROLE-FILE-TRIM"
    if not (control_dir / "SKILL_SPECS.md").exists():
        return "SO21-SKILL-SPECS"
    if _storage_index_out_subtree_needed(control_dir):
        return "SO21-STORAGE-INDEX-OUT-SUBTREE"
    if _custodian_dry_run_manifest_needed(control_dir):
        return "SO21-CUSTODIAN-DRY-RUN-MANIFEST"
    if _dead_automation_and_scheduler_review_needed(control_dir):
        return "SO21-DEAD-AUTOMATION-AND-SCHEDULER-REVIEW"
    if _windows_scheduler_admin_pause_needed(control_dir):
        return "SO21-WINDOWS-SCHEDULER-ADMIN-PAUSE"
    if _windows_scheduler_pause_decision_needed(control_dir):
        return "SO21-WINDOWS-SCHEDULER-PAUSE-DECISION"
    if _automation_rebuild_needed(control_dir):
        return "SO21-AUTOMATION-REBUILD"
    if _automation_activation_decision_needed(control_dir):
        return "SO21-AUTOMATION-ACTIVATION-DECISION"
    if _rep_briefing_first_run_proof_needed(control_dir):
        return "SO21-REP-BRIEFING-FIRST-RUN-PROOF"
    return "SO21-GIT-SYSTEM-CATCH-UP"


def _recommended_reason(task: str) -> str:
    reasons = {
        "SO21-QUEUE-CONTRACT": "the queue contract must exist before generated state can explain active work",
        "SO21-AUTOMATION-REVIEW": "active automations exist and must be reviewed before the 2.1 pause can be trusted",
        "SO21-CUSTODIAN-POLICY": "storage, token, log, archive, temp, stale packet, and dead scheduler ownership is the next missing control layer",
        "SO21-CURRENT-TICKETS-AND-BACKLOG": "active work and backlog should move out of oversized bridge memory into stable control files",
        "SO21-INSTRUCTION-CLEANUP": "the core control files exist, so repeated guidance can be reduced and moved into templates or skills",
        "SO21-AI-USAGE-REPORT": "the control desk now exists, so AI spend, repeated loops, and noisy tasks should become visible",
        "SO21-CODING-PLAN-ARCHIVE": "AI usage visibility shows oversized legacy planning memory should be archived before automation rebuild",
        "SO21-PROMPT-FOLDER-ARCHIVE": "AI usage visibility still shows old plans and prompt folders as high-pressure context",
        "SO21-ROLE-FILE-TRIM": "old manager role files still carry too much repeated context for the new 2.1 front door",
        "SO21-SKILL-SPECS": "repeat workflows should become reusable skill or template specs before automations are rebuilt",
        "SO21-STORAGE-INDEX-OUT-SUBTREE": "the mixed `out/` folder must be classified before any cleanup manifest is proposed",
        "SO21-CUSTODIAN-DRY-RUN-MANIFEST": "classified storage needs a preview-only cleanup manifest before any cleanup can be discussed",
        "SO21-DEAD-AUTOMATION-AND-SCHEDULER-REVIEW": "paused automations and old scheduler ideas must be separated before any automation rebuild",
        "SO21-WINDOWS-SCHEDULER-PAUSE-DECISION": "Windows scheduled tasks are still ready even though Codex app automations are paused",
        "SO21-WINDOWS-SCHEDULER-ADMIN-PAUSE": "Luke approved the pause, but four elevated Windows scheduled tasks still require an Administrator shell",
        "SO21-AUTOMATION-ACTIVATION-DECISION": "the smaller 2.1 automation set is designed; Luke should choose the first Rep briefing pilot activation step",
        "SO21-REP-BRIEFING-FIRST-RUN-PROOF": "the first Rep briefing pilot is active; the remaining proof is its first scheduled read-only briefing run",
        "SO21-GIT-SYSTEM-CATCH-UP": "the 2.1 control model is stable enough to catch Git and system state up deliberately",
        "SO21-AUTOMATION-REBUILD": "core control visibility exists, so only specific useful automations should be reintroduced",
    }
    return reasons.get(task, "next SellerOne 2.1 control task")


def _phase_detail(control_dir: Path) -> str:
    if not (control_dir / "QUEUE_CONTRACT.md").exists():
        return "control inventory complete; queue contract still missing"
    if not (control_dir / "STORAGE_POLICY.md").exists():
        return "queue contract complete; generated current state active; Custodian policy missing"
    if not (control_dir / "CURRENT_TICKETS.md").exists() or not (control_dir / "BACKLOG.md").exists():
        return "queue and Custodian policy exist; current tickets and backlog missing"
    if not (control_dir / "INSTRUCTION_CLEANUP_PLAN.md").exists():
        return "queue, Custodian policy, and current work files exist; instruction cleanup missing"
    if not (control_dir / "AI_USAGE.csv").exists():
        return "core control files and instruction bootstrap exist; AI usage report missing"
    if _coding_plan_archive_needed(control_dir):
        return "AI usage report exists; oversized legacy coding plan still needs archive"
    if _prompt_folder_archive_needed(control_dir):
        return "legacy coding plan archived; old plans and prompt folders still need template/history marking"
    if _role_file_trim_needed(control_dir):
        return "prompt folders archived; old role detail files still need trimming"
    if not (control_dir / "SKILL_SPECS.md").exists():
        return "role files trimmed; repeat workflows still need skill/template specs"
    if _storage_index_out_subtree_needed(control_dir):
        return "skill specs exist; mixed `out/` storage still needs subtree classification"
    if _custodian_dry_run_manifest_needed(control_dir):
        return "`out/` storage is classified; cleanup still needs a preview-only manifest"
    if _dead_automation_and_scheduler_review_needed(control_dir):
        return "cleanup manifest exists or is not required; dead automations and schedulers still need review"
    if _windows_scheduler_admin_pause_needed(control_dir):
        return "Windows scheduler pause is partially applied; elevated runtime tasks still need admin pause"
    if _windows_scheduler_pause_decision_needed(control_dir):
        return "dead automation review found ready Windows scheduler tasks; pause decision needed before automation rebuild"
    if _automation_rebuild_needed(control_dir):
        return "scheduler pause is complete; careful automation rebuild plan still needs to be generated"
    if _automation_activation_decision_needed(control_dir):
        if (control_dir / "SO21_REP_BRIEFING_PILOT.md").exists():
            return "paused Rep briefing pilot exists; activation decision is needed"
        return "automation rebuild plan exists; first pilot creation or activation decision is needed"
    if _rep_briefing_first_run_proof_needed(control_dir):
        return "Rep briefing pilot is active; first scheduled run proof is pending"
    return "core control files and AI usage visibility exist; ready for Git and system catch-up"


def _coding_plan_archive_needed(control_dir: Path) -> bool:
    root = control_dir.parents[1]
    coding_plan = root / "sellerone_manager" / "CODING_PLAN.md"
    archive_marker = control_dir / "CODING_PLAN_ARCHIVE.md"
    return coding_plan.exists() and coding_plan.stat().st_size >= 50_000 and not archive_marker.exists()


def _prompt_folder_archive_needed(control_dir: Path) -> bool:
    if (control_dir / "PROMPT_FOLDER_ARCHIVE.md").exists():
        return False
    rows = _read_csv_rows(control_dir / "AI_USAGE.csv")
    for row in rows:
        if row.get("job_ref") == "PLANS" and row.get("risk_level") == "high":
            return True
    return False


def _role_file_trim_needed(control_dir: Path) -> bool:
    if (control_dir / "ROLE_FILE_TRIM.md").exists():
        return False
    root = control_dir.parents[1]
    targets = [
        root / "sellerone_manager" / "MANAGER_CHAT.md",
        root / "sellerone_manager" / "MANAGER_PROGRESS_TRACKER.md",
        root / "sellerone_manager" / "CYCLE_SUB_MANAGER_CHAT.md",
        root / "sellerone_manager" / "WORKER_CHAT.md",
    ]
    return any(path.exists() and path.stat().st_size >= 10_000 for path in targets)


def _storage_index_out_subtree_needed(control_dir: Path) -> bool:
    path = control_dir / "STORAGE_INDEX.csv"
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8", errors="ignore").lower()
    return "needs out subtree index" in text or "needs out/ subtree index" in text


def _custodian_dry_run_manifest_needed(control_dir: Path) -> bool:
    return not (
        (control_dir / "CUSTODIAN_DRY_RUN_MANIFEST.csv").exists()
        or (control_dir / "CUSTODIAN_DRY_RUN_MANIFEST.md").exists()
    )


def _dead_automation_and_scheduler_review_needed(control_dir: Path) -> bool:
    return not (control_dir / "DEAD_AUTOMATION_AND_SCHEDULER_REVIEW.md").exists()


def _windows_scheduler_pause_decision_needed(control_dir: Path) -> bool:
    if (control_dir / "WINDOWS_SCHEDULER_PAUSE_DECISION.md").exists():
        return False
    rows = _read_csv_rows(control_dir / "DEAD_AUTOMATION_AND_SCHEDULER_REVIEW.csv")
    return any(
        row.get("source_type") == "windows_scheduler"
        and row.get("luke_decision_required") == "yes"
        for row in rows
    )


def _windows_scheduler_admin_pause_needed(control_dir: Path) -> bool:
    rows = _read_csv_rows(control_dir / "WINDOWS_SCHEDULER_PAUSE_PROOF.csv")
    return any(
        row.get("after_state") == "Ready"
        and row.get("exit_code") not in {"", "0"}
        for row in rows
    )


def _automation_rebuild_needed(control_dir: Path) -> bool:
    return not (
        (control_dir / "AUTOMATION_REBUILD.md").exists()
        and (control_dir / "AUTOMATION_REBUILD_PLAN.csv").exists()
    )


def _automation_activation_decision_needed(control_dir: Path) -> bool:
    return not (control_dir / "AUTOMATION_ACTIVATION_DECISION.md").exists()


def _rep_briefing_first_run_proof_needed(control_dir: Path) -> bool:
    return (
        (control_dir / "SO21_REP_BRIEFING_ACTIVATION.md").exists()
        and not (control_dir / "SO21_REP_BRIEFING_FIRST_RUN_PROOF.md").exists()
    )


def _plain_status(
    *,
    mot_summary: dict[str, Any],
    active_automation_count: int,
    approved_active_automation_count: int,
    unapproved_active_automation_count: int,
    active_work_count: int,
    blocked_work_count: int,
    recommended_next: str,
) -> str:
    pieces = [
        "SellerOne is in SellerOne 2.1 control stabilisation.",
        f"The queue has {active_work_count} active non-Luke tickets and {blocked_work_count} Luke-blocked tickets.",
        "The latest MOT status is "
        f"{mot_summary['status']} with {_plural(mot_summary['fail_count'], 'fail')}, "
        f"{_plural(mot_summary['warn_count'], 'warning')}, and {_plural(mot_summary['decision_count'], 'decision')}.",
    ]
    if unapproved_active_automation_count:
        pieces.append(f"There are {unapproved_active_automation_count} unapproved active automations, so automation review is required.")
    elif approved_active_automation_count:
        pieces.append(f"There is {approved_active_automation_count} approved active pilot automation.")
    elif active_automation_count:
        pieces.append(f"There are {active_automation_count} active automations.")
    else:
        pieces.append("Codex automations are paused.")
    pieces.append(f"The recommended next 2.1 task is {recommended_next}.")
    return " ".join(pieces)


def _format_problem_rows(title: str, rows: list[dict[str, Any]]) -> list[str]:
    lines = [f"## {title}", ""]
    if not rows:
        lines.extend(["- None visible in latest MOT evidence.", ""])
        return lines
    for row in rows[:5]:
        flow = _text(row.get("flow")) or "?"
        check = _text(row.get("check")) or _text(row.get("work_item_id")) or "unknown_check"
        root_cause = _text(row.get("root_cause_guess"))
        action = _text(row.get("manager_action"))
        summary = _text(row.get("summary"))
        value = _text(row.get("value"))
        detail = root_cause or action or summary or value or "No summary supplied."
        if action and action != detail:
            detail = f"{detail} Next: {action}"
        lines.append(f"- {flow} / {check}: {_shorten(detail, 190)}")
    lines.append("")
    return lines


def _format_work_rows(rows: list[dict[str, str]], *, empty_message: str) -> list[str]:
    if not rows:
        return [f"- {empty_message}"]
    lines = []
    for row in rows[:8]:
        status = STATUS_LABELS.get(row.get("status", ""), row.get("status", "unknown"))
        job_ref = _text(row.get("job_ref")) or _text(row.get("task_id")) or "unknown-job"
        title = _text(row.get("title")) or "Untitled ticket"
        flow = _text(row.get("flow")) or "?"
        luke = " Luke decision needed." if _text(row.get("luke_action_required")) == "1" else ""
        lines.append(f"- {job_ref} ({flow}, {status}): {_shorten(title, 120)}.{luke}")
    if len(rows) > 8:
        lines.append(f"- Plus {len(rows) - 8} more packet rows.")
    return lines


def _work_sort_key(row: dict[str, str]) -> tuple[int, int, str]:
    status_rank = {
        "blocked_needs_luke": 0,
        "retest_failed": 1,
        "fixed_needs_retest": 2,
        "in_progress": 3,
        "reopened": 4,
        "approved": 5,
        "parked": 6,
        "proved": 7,
    }.get(row.get("status", ""), 9)
    priority_rank = {"urgent": 0, "high": 1, "medium": 2, "low": 3}.get(row.get("priority", ""), 4)
    return status_rank, priority_rank, row.get("job_ref", row.get("task_id", ""))


def _toml_field(text: str, field: str) -> str:
    match = re.search(rf'^{re.escape(field)}\s*=\s*"([^"]*)"', text, flags=re.MULTILINE)
    return match.group(1) if match else ""


def _latest_observed(rows: list[dict[str, str]]) -> str:
    values = [row.get("observed_utc", "") for row in rows if row.get("observed_utc")]
    return max(values) if values else ""


def _status_from_counts(counts: Counter[str]) -> str:
    if counts.get("fail"):
        return "fail"
    if counts.get("decision_needed"):
        return "decision_needed"
    if counts.get("warn"):
        return "warn"
    if counts.get("ok"):
        return "ok"
    return "unknown"


def _int_text(value: object) -> str:
    if value is None:
        return "0"
    try:
        return str(int(value))
    except (TypeError, ValueError):
        return "0"


def _text(value: object) -> str:
    return str(value).strip() if value is not None else ""


def _shorten(value: str, limit: int) -> str:
    text = " ".join(value.split())
    if len(text) <= limit:
        return text
    return text[: max(0, limit - 3)].rstrip() + "..."


def _plural(value: object, singular: str) -> str:
    count = _int_text(value)
    suffix = "" if count == "1" else "s"
    if singular.endswith("y") and suffix:
        return f"{count} {singular[:-1]}ies"
    return f"{count} {singular}{suffix}"
