from __future__ import annotations


SUPPLIER_REGISTRY_COLUMNS = [
    "supplier_id",
    "supplier_name",
    "source_type",
    "source_subtype",
    "source_url",
    "source_folder_path",
    "existing_supplier_config_path",
    "converter_id",
    "normal_refresh_days",
    "minimum_rescan_days",
    "large_file_flag",
    "manual_request_required_flag",
    "priority_band",
    "active_flag",
    "notes",
]

PRICE_LIST_BATCH_COLUMNS = [
    "batch_id",
    "supplier_id",
    "source_type",
    "source_subtype",
    "source_received_at_utc",
    "source_file_path",
    "source_file_hash",
    "converted_file_path",
    "source_row_count",
    "valid_row_count",
    "held_row_count",
    "new_row_count",
    "changed_row_count",
    "eligible_row_count",
    "skipped_cooldown_row_count",
    "batch_status",
    "status_reason",
    "updated_at_utc",
]

BATCH_ROW_COLUMNS = [
    "batch_id",
    "supplier_id",
    "row_key",
    "supplier_sku",
    "supplier_title",
    "barcode",
    "unit_cost",
    "currency",
    "vat_rate",
    "unit_code",
    "pack_size",
    "pack_cost",
    "moq",
    "source_row_hash",
    "row_change_status",
    "scan_eligibility",
    "eligibility_reason",
    "last_memory_key",
    "cooldown_until_utc",
]

BARCODE_SCAN_MEMORY_COLUMNS = [
    "memory_key",
    "memory_scope",
    "supplier_id",
    "barcode",
    "asin",
    "last_result_status",
    "last_fail_code",
    "last_stage",
    "last_scanned_at_utc",
    "cooldown_until_utc",
    "cooldown_basis",
    "attempt_count",
    "last_batch_id",
    "last_row_hash",
    "updated_at_utc",
]

MANAGER_DECISION_COLUMNS = [
    "decision_id",
    "decided_at_utc",
    "recommended_action",
    "supplier_id",
    "batch_id",
    "reason_code",
    "estimated_scan_rows",
    "estimated_skip_rows",
    "f061_owner_status",
    "safe_to_handoff_flag",
    "notes",
]

MANAGER_HEALTH_COLUMNS = [
    "check",
    "status",
    "value",
    "notes",
    "observed_utc",
    "source_path",
]

SOURCE_ACQUISITION_COLUMNS = [
    "supplier_id",
    "supplier_name",
    "source_type",
    "source_subtype",
    "source_state",
    "status",
    "source_location",
    "latest_source_path",
    "latest_source_name",
    "latest_source_mtime_utc",
    "file_count",
    "operator_action",
    "checked_at_utc",
    "notes",
]

BATCH_SCAN_ELIGIBILITY_COLUMNS = [
    "batch_id",
    "supplier_id",
    "row_key",
    "supplier_sku",
    "barcode",
    "unit_cost",
    "base_eligibility",
    "scan_decision",
    "decision_reason",
    "memory_key",
    "cooldown_until_utc",
    "observed_utc",
]

NEXT_ACTION_SKIP_REASON_COLUMNS = [
    "supplier_id",
    "decision_reason",
    "rows",
]

QUEUE_CONTROL_COLUMNS = [
    "supplier_id",
    "control_state",
    "priority_rank",
    "reason",
    "updated_at_utc",
]

F061_STAGED_ACTIVE_RUN_COLUMNS = [
    "run_id",
    "supplier_id",
    "supplier_name",
    "row_key",
    "supplier_sku",
    "barcode",
    "supplier_title",
    "unit_cost",
    "currency",
    "vat_rate",
    "scan_status",
    "scan_reason",
    "attempt_count",
    "last_attempt_utc",
    "finished_utc",
    "source_seen_at_utc",
]

F061_STAGED_RUN_STATE_COLUMNS = [
    "supplier_id",
    "supplier_name",
    "run_id",
    "run_status",
    "source_url",
    "source_file_path",
    "source_seen_at_utc",
    "normalized_utc",
    "total_rows",
    "pending_rows",
    "done_rows",
    "failed_rows",
    "held_rows",
    "next_row_index",
    "updated_at_utc",
    "completed_at_utc",
]

F061_HANDOFF_PREVIEW_COLUMNS = [
    "handoff_id",
    "built_at_utc",
    "mode",
    "supplier_id",
    "supplier_name",
    "batch_id",
    "run_id",
    "staged_rows",
    "technical_ready_flag",
    "approval_state",
    "approval_id",
    "live_apply_allowed",
    "f061_idle_status",
    "block_reason",
    "staged_active_run_path",
    "staged_run_state_path",
]

F061_HANDOFF_APPROVAL_COLUMNS = [
    "approval_id",
    "supplier_id",
    "batch_id",
    "approval_state",
    "approved_by",
    "approved_at_utc",
    "expires_at_utc",
    "reason",
]

F061_HANDOFF_APPLY_PREVIEW_COLUMNS = [
    "apply_id",
    "built_at_utc",
    "mode",
    "supplier_id",
    "supplier_name",
    "batch_id",
    "run_id",
    "staged_rows",
    "apply_ready_flag",
    "live_write_attempted",
    "live_write_succeeded",
    "block_reason",
    "backup_dir",
    "backup_manifest_path",
    "live_active_run_path",
    "live_run_state_path",
]

F061_HANDOFF_BACKUP_MANIFEST_COLUMNS = [
    "backup_id",
    "built_at_utc",
    "source_contract",
    "source_path",
    "backup_path",
    "row_count",
    "notes",
]

F061_RECOVERY_PROGRESS_COLUMNS = [
    "imported_at_utc",
    "supplier_id",
    "batch_id",
    "legacy_run_id",
    "legacy_total_rows",
    "legacy_pending_rows",
    "legacy_done_rows",
    "legacy_failed_rows",
    "pending_source_rows",
    "pending_matched_rows",
    "pending_held_rows",
    "pending_unmatched_rows",
    "manager_valid_rows",
    "manager_scan_now_rows",
    "manager_recovery_skipped_rows",
    "manager_held_rows",
    "legacy_active_run_path",
    "legacy_run_state_path",
]

F061_LIVE_TRIAL_SAMPLE_COLUMNS = [
    "trial_id",
    "built_at_utc",
    "supplier_id",
    "supplier_name",
    "batch_id",
    "source_received_at_utc",
    "selected_rows",
    "held_reason",
    "sample_active_run_path",
    "sample_run_state_path",
]

LIVE_CYCLE_STATUS_COLUMNS = [
    "observed_utc",
    "run_id",
    "owner_pid",
    "state",
    "active_supplier_id",
    "active_f061_run_id",
    "pending_rows",
    "last_action",
    "last_action_status",
    "chunk_rows",
    "drain_ready",
    "notes",
]

LIVE_CYCLE_EVENT_COLUMNS = [
    "event_utc",
    "cycle_run_id",
    "event_type",
    "supplier_id",
    "f061_run_id",
    "status",
    "rows",
    "notes",
]

REVIEW_HANDOFF_STATUS_COLUMNS = [
    "observed_utc",
    "supplier_id",
    "supplier_name",
    "run_id",
    "handoff_state",
    "ready_to_publish_flag",
    "block_reason",
    "health_status",
    "run_status",
    "total_rows",
    "pending_rows",
    "done_rows",
    "failed_rows",
    "held_rows",
    "active_pending_rows",
    "active_run_rows",
    "f061_child_active_flag",
    "live_cycle_state",
    "screening_rows",
    "screening_completed_rows",
    "screening_pending_rows",
    "screening_login_backtrack_rows",
    "screening_pass_rows",
    "screening_timeout_rows",
    "first_check_pass_rows",
    "scrape_evidence_rows",
    "completed_at_utc",
    "source_file_path",
    "source_seen_at_utc",
    "notes",
]

REVIEW_HANDOFF_MANIFEST_COLUMNS = [
    "built_at_utc",
    "supplier_id",
    "supplier_name",
    "run_id",
    "review_snapshot_id",
    "source_file_path",
    "source_seen_at_utc",
    "completed_at_utc",
    "pass_review_rows",
    "near_miss_review_rows",
    "hard_reject_rows",
    "pass_review_path",
    "near_miss_review_path",
    "summary_path",
    "handoff_dir",
    "published_to_operator_latest_flag",
    "ai_gate_status",
    "ai_gate_observed_utc",
    "ai_gate_version",
    "ai_gate_health_path",
    "ai_review_queue_path",
    "ai_gate_decision_path",
    "codex_ai_decision_path",
    "ai_gate_checklist_path",
    "ai_gate_rule_suggestion_path",
    "ai_gate_rescan_queue_path",
    "ai_gate_removed_audit_path",
    "ai_gate_manual_review_path",
    "raw_candidate_manifest_path",
    "raw_pass_review_path",
    "raw_near_miss_review_path",
    "ai_gate_fail_rows",
    "ai_gate_warn_rows",
    "ai_gate_clear_rows",
    "ai_gate_manual_rows",
    "ai_gate_rescan_rows",
    "ai_gate_removed_rows",
    "ai_gate_quality_status",
    "ai_gate_quality_fail_checks",
    "ai_gate_quality_warn_checks",
    "ai_gate_quality_report_path",
    "operator_ready_flag",
    "block_reason",
    "notes",
]

REVIEW_CANDIDATE_MANIFEST_COLUMNS = [
    "built_at_utc",
    "supplier_id",
    "supplier_name",
    "run_id",
    "review_snapshot_id",
    "source_file_path",
    "source_seen_at_utc",
    "completed_at_utc",
    "raw_pass_review_rows",
    "raw_near_miss_review_rows",
    "hard_reject_rows",
    "raw_pass_review_path",
    "raw_near_miss_review_path",
    "raw_summary_path",
    "handoff_dir",
    "operator_ready_flag",
    "block_reason",
    "notes",
]

TEST_MODE_CYCLE_RUN_COLUMNS = [
    "cycle_id",
    "started_at_utc",
    "completed_at_utc",
    "max_iterations",
    "acquisition_ready_rows",
    "downloaded_sources",
    "api_fetched_sources",
    "imported_batches",
    "scanner_iterations",
    "result_rows",
    "processed_suppliers",
    "final_selected_supplier_id",
    "status",
    "notes",
]

TEST_MODE_CYCLE_STEP_COLUMNS = [
    "cycle_id",
    "step_index",
    "step_name",
    "supplier_id",
    "batch_id",
    "status",
    "rows",
    "notes",
    "observed_utc",
]

PLACEHOLDER_SCANNER_RESULT_COLUMNS = [
    "result_id",
    "batch_id",
    "supplier_id",
    "row_key",
    "supplier_sku",
    "barcode",
    "placeholder_outcome",
    "result_status",
    "fail_code",
    "last_stage",
    "memory_scope",
    "cooldown_days",
    "scanned_at_utc",
    "notes",
]

STATUS_DASHBOARD_COLUMNS = [
    "queue_position",
    "supplier_id",
    "supplier_name",
    "source_method",
    "source_location",
    "file_state",
    "queue_state",
    "operator_action",
    "control_state",
    "price_list_date",
    "bot_status",
    "web_unprocessed",
    "web_pass",
    "web_fail",
    "web_rescan",
    "second_unprocessed",
    "second_pass",
    "second_fail",
]


TEST_MODE_OUTPUT_COLUMNS = {
    "supplier_registry": SUPPLIER_REGISTRY_COLUMNS,
    "price_list_batches": PRICE_LIST_BATCH_COLUMNS,
    "batch_rows": BATCH_ROW_COLUMNS,
    "barcode_scan_memory": BARCODE_SCAN_MEMORY_COLUMNS,
    "manager_decisions": MANAGER_DECISION_COLUMNS,
    "health": MANAGER_HEALTH_COLUMNS,
    "source_acquisition_status": SOURCE_ACQUISITION_COLUMNS,
    "batch_scan_eligibility": BATCH_SCAN_ELIGIBILITY_COLUMNS,
    "next_action_skip_reasons": NEXT_ACTION_SKIP_REASON_COLUMNS,
    "queue_controls": QUEUE_CONTROL_COLUMNS,
    "f061_handoff_staged_active_run": F061_STAGED_ACTIVE_RUN_COLUMNS,
    "f061_handoff_staged_run_state": F061_STAGED_RUN_STATE_COLUMNS,
    "f061_handoff_preview": F061_HANDOFF_PREVIEW_COLUMNS,
    "f061_handoff_approvals": F061_HANDOFF_APPROVAL_COLUMNS,
    "f061_handoff_apply_preview": F061_HANDOFF_APPLY_PREVIEW_COLUMNS,
    "f061_handoff_apply_backups": F061_HANDOFF_BACKUP_MANIFEST_COLUMNS,
    "f061_recovery_progress": F061_RECOVERY_PROGRESS_COLUMNS,
    "f061_live_trial_samples": F061_LIVE_TRIAL_SAMPLE_COLUMNS,
    "live_cycle_status": LIVE_CYCLE_STATUS_COLUMNS,
    "live_cycle_events": LIVE_CYCLE_EVENT_COLUMNS,
    "live_cycle_health": MANAGER_HEALTH_COLUMNS,
    "review_handoff_status": REVIEW_HANDOFF_STATUS_COLUMNS,
    "review_handoff_health": MANAGER_HEALTH_COLUMNS,
    "review_handoff_manifest": REVIEW_HANDOFF_MANIFEST_COLUMNS,
    "review_candidate_manifest": REVIEW_CANDIDATE_MANIFEST_COLUMNS,
    "test_mode_cycle_runs": TEST_MODE_CYCLE_RUN_COLUMNS,
    "test_mode_cycle_steps": TEST_MODE_CYCLE_STEP_COLUMNS,
    "placeholder_scanner_results": PLACEHOLDER_SCANNER_RESULT_COLUMNS,
    "status_dashboard": STATUS_DASHBOARD_COLUMNS,
}


def get_output_columns(name: str) -> list[str]:
    try:
        return list(TEST_MODE_OUTPUT_COLUMNS[name])
    except KeyError as exc:
        raise ValueError(f"unknown price-list manager output: {name}") from exc
